### ISSUE TITLE
Doc update requests

### ISSUE THREAD

**Issue by StephenTangCook** [themashcodee/slack-blocks-to-jsx#8]
https://github.com/themashcodee/slack-blocks-to-jsx/blob/9d462cad3719baa2ef7ed85f5243d5c1cfb6616a/readme.md?plain=1#L62

Listing out the hooks would be helpful for the docs! 🙏 

https://github.com/themashcodee/slack-blocks-to-jsx/blob/9d462cad3719baa2ef7ed85f5243d5c1cfb6616a/readme.md?plain=1#L77

Would be good to break down the support for all of the rich text elements. Correct me if I'm wrong, but do you support `date` yet?

**Comment by themashcodee** [comment]
@StephenTangCook Thanks again.

1. I will add the hooks to the docs with detailed explaination.
2. I will also break down the Rich Text Block.
3. I don't really support it yet because I could not understand how we can actually send a date through slack (we can use mentions, broadcast etc directly from slack without any api). I would very grateful if you could help me understand or give me an example of date (rich text sextion element).

**Comment by themashcodee** [comment]
resolved in v0.3.4
